# Generated by Django 4.2.6 on 2023-11-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_сoordinate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сoordinate',
            new_name='Coordinate',
        ),
    ]
