# Generated by Django 4.2.6 on 2023-10-26 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('media_path', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents_post_incident',
            },
        ),
    ]
