# Generated by Django 4.2.6 on 2023-10-26 11:49

from django.db import migrations, models
import django.db.models.deletion
import incidents.models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_postincident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postincident',
            name='media_path',
        ),
        migrations.AddField(
            model_name='postincident',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=incidents.models._get_file_path),
        ),
        migrations.AlterField(
            model_name='postincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='incidents.incident'),
        ),
    ]
